### ISSUE TITLE
Adding a part with a manufacturer causes error

### ISSUE THREAD

**Issue by aaronbeekay** [mpkasp/django-bom#32] opened 2020-01-05 20:25 UTC
Entering a value in the "Manufacturer part number" and "Create a New Manufacturer" fields on the "Create a Part" page (`/bom/create-part/`) causes an error that results in a 500 being returned.

Reproduce steps:

1. Attempt to create a part with the following properties:
  - P/N class: 101 (the first in my list)
  - Description: `example part`
  - Manufacturer part number: `123`
  - Manufacturer: (leave field at default `---------` value)
  - OR Create A New Manufacturer: `abc`

Expected result: part gets created
Actual result: 500

I don't have an installation of IndaBOM locally yet so I don't have any way to get more debug information right now 😬

**Comment by mpkasp** [comment] 2020-01-06 02:06
Great - thanks for the steps to reproduce. I see it and will look into it!

**Comment by mpkasp** [comment] 2020-01-06 03:08
Ok looks like this is due to a get_or_create with an `iexact` on the name field. Should be fixed in Robert's pull request. Here:

https://github.com/mpkasp/django-bom/pull/30/commits/d525bdb8c68f44480754bef00b3f723fc6bf4261#diff-c18c1d51b4615ea4d3f2d066b6f5b031R842

**Closed** 2020-01-07 04:42 UTC
